### ISSUE TITLE
逆水寒手游PC模拟器有没有

### ISSUE THREAD

**Issue by martjay** [happyme531/clxTools#14]
逆水寒手游PC模拟器有没有

**Comment by happyme531** [comment]
https://github.com/happyme531/clxTools/blob/master/%E6%A5%9A%E7%95%99%E9%A6%99%E9%9F%B3%E4%B9%90%E7%9B%92_pc%E7%89%88/%E9%80%86%E6%B0%B4%E5%AF%92%E6%89%8B%E6%B8%B8_pc%E7%89%88.bmtp
