### ISSUE TITLE
新增网络曲库

### ISSUE THREAD

**Issue by pyh919597378** [happyme531/clxTools#17]
大佬有什么办法可以在原有的基础上新增一个网络曲库吗，json数据全部都存在服务器上，然后通过post获取json数据，同时还能保留收藏的功能

**Comment by happyme531** [comment]
如果你可以给我弄个服务器再写个后端，那我就加个网络曲库功能

**Comment by happyme531** [comment]
不过这有必要吗，midi文件又不大，每个文件几十KB，几千个文件也就几百MB，这还是不压缩的情况。直接本地曲库就完事了

**Comment by pyh919597378** [comment]
后端已经有了，“http://autoplay.chimomo.cn/api/v1/midi/list”获取歌曲列表，“http://autoplay.chimomo.cn/api/v1/midi/{id}”根据歌曲列表中每首歌的ID获取json源码。主要里面的歌都是我们自己制作出来适配21键的标准midi文件，有些有时候问题还会删除修改重新上传。群友也有自己上传的

**Comment by happyme531** [comment]
可以啊，我过几天看看

**Comment by happyme531** [comment]
725e8d67f222e0c80cfa876e4b3a20f1d6379a52
