### ISSUE TITLE
关于增加新游戏键位

### ISSUE THREAD

**Issue by pyh919597378** [happyme531/clxTools#18]
作者大大你好。为了新增”心动小镇“游戏我根据你的脚本布局更新了gameProfile.js文件。
有三处地方改动，如图。我新增之后实际上运行脚本后，在选择游戏对话框中并没有出现心动小镇，能否抽空帮忙看一下问题出在哪里？
![NO1](https://github.com/user-attachments/assets/a9e468df-8aee-4576-97e9-9caf7976e85a)
![NO2](https://github.com/user-attachments/assets/148acbeb-4f36-4a90-a487-5fc7a461c503)
![NO3](https://github.com/user-attachments/assets/9c2920f5-9cf6-4b3e-8290-0b626450e3e9)

**Comment by happyme531** [comment]
https://github.com/happyme531/clxTools/blob/0aa43d8d02cfc6c355d9dfffc09635ce55193421/%E6%A5%9A%E7%95%99%E9%A6%99%E9%9F%B3%E4%B9%90%E7%9B%92/main.js#L40

增加版本号再试试
（这个逻辑其实挺糟糕的，改天重构一下？）

**Comment by pyh919597378** [comment]
增加版本号就可以了，感谢作者大大，增加之后他那个配置就自动初始化了。之前我重新拉了完整的包，在运行之前新增上面的键位布局都没成功触发自动初始化。
