### ISSUE TITLE
音乐盒在vivo渠道服客户端上报错

### ISSUE THREAD

**Issue by longli928** [happyme531/clxTools#2]
我将检测的包名改成vivo端的包名"com.netease.wyclx.vivo"后报错：TypeError:Cannot read property "notes" from undefined(<main>#183)

**Comment by happyme531** [comment]
这与渠道服客户端无关，貌似是因为选择的文件无法打开，不存在，或者格式不对..

**Comment by happyme531** [comment]
播放自带的那个示例也是这样吗？

**Comment by longli928** [comment]
> 播放自带的那个示例也是这样吗？

是的，我用20191117的releases里的脚本重新改包名打包后可以正常弹，只不过提示演奏完毕的吐司弹出的时候报错。

**Comment by happyme531** [comment]
抱歉，那个release版本没有全面测试，还有一点小bug。master分支当前版本似乎已经没有这个问题了

**Comment by longli928** [comment]
> 抱歉，那个release版本没有全面测试，还有一点小bug。master分支当前版本似乎已经没有这个问题了

试了一下，正常运行，感谢开发
